services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
      - ../env/.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 10s
      retries: 5

  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: fastapi_app
    restart: always
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ../env/.env
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app
    command: ["/app/start.sh"]

volumes:
  postgres_data:
